### PR TITLE
fix: adjust coordinate updating to fix firefox bug

### LINKED ISSUE #23: handle firefox drag-drop error
on Firefox, when notes are dragged and dropped they move to the top left of the window instead of their dropped location

### PR DESCRIPTION
**Pull request by hagoptaminian**
closes #23

### CODE REVIEW

**Comment by hagoptaminian** [comment]
@juancarlosfarah check it out. After a ton of experimentation and frustration - the drag events are not consistent across the browsers - I realized that I might be able to get the dragged note coordinates from the parent/main div (via its `onDragOver` method), rather than from the notes themselves. This worked! I tested it in both standalone and 'live' mode and with all browsers simultaneously, and it is working perfectly, but please also double-check by doing the same...

**Review by juancarlosfarah — APPROVED** [review]
🚀 

Tested on Safari, Firefox, Chrome, and Brave.

Just a quick question. In this case aren't you doing a ton of updates to the state? If so, would it make sense to throttle the call?

**Comment by juancarlosfarah** [comment]
@hagoptaminian, since it's OK to be off by a couple pixels, you can debounce the `setState` function of the `dragOver` event so that it's only called every X millis. Even if it's X<100ms, it will save a ton of `setState` calls. What do you think? You can try different X values and compare the effectiveness by keeping a counter of how many times `setState` is called.

**Comment by hagoptaminian** [comment]
@juancarlosfarah interesting... created an issue with it here: #25

**Pull request merged**
